# -*- coding: utf-8 -*-
# Generated by https://github.com/connectrpc/connect-python.  DO NOT EDIT!
# source: civican/schemas/proto/lobbycanada/v1/lobbycanada.proto

from collections.abc import AsyncGenerator, AsyncIterator, Iterable, Iterator, Mapping
from typing import Protocol

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.codec import Codec
from connectrpc.compression import Compression
from connectrpc.errors import ConnectError
from connectrpc.interceptor import Interceptor, InterceptorSync
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.request import Headers, RequestContext
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, Endpoint, EndpointSync
import civican.schemas.proto.lobbycanada.v1.lobbycanada_pb2 as civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2


class LobbyCanadaService(Protocol):
    async def list_registrations(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_registration(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def list_communications(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_communication(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def cross_reference_bill(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")

    async def get_top_lobbied_bills(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class LobbyCanadaServiceASGIApplication(ConnectASGIApplication[LobbyCanadaService]):
    def __init__(self, service: LobbyCanadaService | AsyncGenerator[LobbyCanadaService], *, interceptors: Iterable[Interceptor]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/lobbycanada.v1.LobbyCanadaService/ListRegistrations": Endpoint.unary(
                    method=MethodInfo(
                        name="ListRegistrations",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_registrations,
                ),
                "/lobbycanada.v1.LobbyCanadaService/GetRegistration": Endpoint.unary(
                    method=MethodInfo(
                        name="GetRegistration",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_registration,
                ),
                "/lobbycanada.v1.LobbyCanadaService/ListCommunications": Endpoint.unary(
                    method=MethodInfo(
                        name="ListCommunications",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.list_communications,
                ),
                "/lobbycanada.v1.LobbyCanadaService/GetCommunication": Endpoint.unary(
                    method=MethodInfo(
                        name="GetCommunication",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_communication,
                ),
                "/lobbycanada.v1.LobbyCanadaService/CrossReferenceBill": Endpoint.unary(
                    method=MethodInfo(
                        name="CrossReferenceBill",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.cross_reference_bill,
                ),
                "/lobbycanada.v1.LobbyCanadaService/GetTopLobbiedBills": Endpoint.unary(
                    method=MethodInfo(
                        name="GetTopLobbiedBills",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.get_top_lobbied_bills,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lobbycanada.v1.LobbyCanadaService"


class LobbyCanadaServiceClient(ConnectClient):
    async def list_registrations(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRegistrations",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_registration(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRegistration",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_communications(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCommunications",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_communication(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCommunication",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def cross_reference_bill(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CrossReferenceBill",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_top_lobbied_bills(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsResponse:
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTopLobbiedBills",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )





class LobbyCanadaServiceSync(Protocol):
    def list_registrations(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_registration(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def list_communications(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_communication(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def cross_reference_bill(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")
    def get_top_lobbied_bills(self, request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsRequest, ctx: RequestContext) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsResponse:
        raise ConnectError(Code.UNIMPLEMENTED, "Not implemented")


class LobbyCanadaServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(self, service: LobbyCanadaServiceSync, interceptors: Iterable[InterceptorSync]=(), read_max_bytes: int | None = None, compressions: Iterable[Compression] | None = None, codecs: Iterable[Codec] | None = None) -> None:
        super().__init__(
            endpoints={
                "/lobbycanada.v1.LobbyCanadaService/ListRegistrations": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListRegistrations",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_registrations,
                ),
                "/lobbycanada.v1.LobbyCanadaService/GetRegistration": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetRegistration",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_registration,
                ),
                "/lobbycanada.v1.LobbyCanadaService/ListCommunications": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListCommunications",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.list_communications,
                ),
                "/lobbycanada.v1.LobbyCanadaService/GetCommunication": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetCommunication",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_communication,
                ),
                "/lobbycanada.v1.LobbyCanadaService/CrossReferenceBill": EndpointSync.unary(
                    method=MethodInfo(
                        name="CrossReferenceBill",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.cross_reference_bill,
                ),
                "/lobbycanada.v1.LobbyCanadaService/GetTopLobbiedBills": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetTopLobbiedBills",
                        service_name="lobbycanada.v1.LobbyCanadaService",
                        input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsRequest,
                        output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.get_top_lobbied_bills,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/lobbycanada.v1.LobbyCanadaService"


class LobbyCanadaServiceClientSync(ConnectClientSync):
    def list_registrations(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListRegistrations",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListRegistrationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_registration(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetRegistration",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetRegistrationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def list_communications(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListCommunications",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.ListCommunicationsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_communication(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetCommunication",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetCommunicationResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def cross_reference_bill(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CrossReferenceBill",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.CrossReferenceBillResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    def get_top_lobbied_bills(
        self,
        request: civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None,
        timeout_ms: int | None = None,
    ) -> civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsResponse:
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetTopLobbiedBills",
                service_name="lobbycanada.v1.LobbyCanadaService",
                input=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsRequest,
                output=civican_dot_schemas_dot_proto_dot_lobbycanada_dot_v1_dot_lobbycanada__pb2.GetTopLobbiedBillsResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )


