# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: civican/schemas/proto/lobbycanada/v1/lobbycanada.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6civican/schemas/proto/lobbycanada/v1/lobbycanada.proto\x12\x0elobbycanada.v1\"\x98\x03\n\x11LobbyRegistration\x12\'\n\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12\'\n\x0fregistrant_name\x18\x02 \x01(\tR\x0eregistrantName\x12&\n\x0f\x63lient_org_name\x18\x03 \x01(\tR\rclientOrgName\x12\x12\n\x04type\x18\x04 \x01(\tR\x04type\x12\x16\n\x06status\x18\x05 \x01(\tR\x06status\x12%\n\x0e\x65\x66\x66\x65\x63tive_date\x18\x06 \x01(\tR\reffectiveDate\x12\x1f\n\x0bposted_date\x18\x07 \x01(\tR\npostedDate\x12\'\n\x0fsubject_matters\x18\x08 \x03(\tR\x0esubjectMatters\x12\x33\n\x15legislative_proposals\x18\t \x03(\tR\x14legislativeProposals\x12\x37\n\x17government_institutions\x18\n \x03(\tR\x16governmentInstitutions\"\xd6\x03\n\x12LobbyCommunication\x12)\n\x10\x63ommunication_id\x18\x01 \x01(\tR\x0f\x63ommunicationId\x12\'\n\x0fregistration_id\x18\x02 \x01(\tR\x0eregistrationId\x12&\n\x0f\x63lient_org_name\x18\x03 \x01(\tR\rclientOrgName\x12-\n\x12\x63ommunication_date\x18\x04 \x01(\tR\x11\x63ommunicationDate\x12\x1f\n\x0bposted_date\x18\x05 \x01(\tR\npostedDate\x12#\n\rlobbyist_name\x18\x06 \x01(\tR\x0clobbyistName\x12\x1b\n\tdpoh_name\x18\x07 \x01(\tR\x08\x64pohName\x12\x1d\n\ndpoh_title\x18\x08 \x01(\tR\tdpohTitle\x12\x35\n\x16government_institution\x18\t \x01(\tR\x15governmentInstitution\x12\'\n\x0fsubject_matters\x18\n \x03(\tR\x0esubjectMatters\x12\x33\n\x15legislative_proposals\x18\x0b \x03(\tR\x14legislativeProposals\"\xbe\x01\n\x11LobbyScrapeResult\x12\x18\n\x07success\x18\x01 \x01(\x08R\x07success\x12#\n\rtotal_scraped\x18\x02 \x01(\x05R\x0ctotalScraped\x12\x33\n\x15registrations_scraped\x18\x03 \x01(\x05R\x14registrationsScraped\x12\x35\n\x16\x63ommunications_scraped\x18\x04 \x01(\x05R\x15\x63ommunicationsScrapedb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'civican.schemas.proto.lobbycanada.v1.lobbycanada_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LOBBYREGISTRATION']._serialized_start=75
  _globals['_LOBBYREGISTRATION']._serialized_end=483
  _globals['_LOBBYCOMMUNICATION']._serialized_start=486
  _globals['_LOBBYCOMMUNICATION']._serialized_end=956
  _globals['_LOBBYSCRAPERESULT']._serialized_start=959
  _globals['_LOBBYSCRAPERESULT']._serialized_end=1149
# @@protoc_insertion_point(module_scope)
